version: "3.3"
services:
  ticker-exercise:
    container_name: ticker-exercise
    build:
      context: ticker-exercise
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    container_name: pg_graph_recon
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
