version: "3.3"
services:
  ticker-exercise:
    container_name: ticker_exercise
    build:
      context: ticker-exercise
    depends_on:
      - database

  database:
    image: postgres:13
    restart: always
    container_name: database_ticker_exercise
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
